### ISSUE TITLE
Cannot build example

### ISSUE THREAD

**Issue by RomanMinenok** [dropbox/djinni#146]
Hi guys, I just started working with Djinni and it looks promising. I am following README in example folder and have some issues with that. 

Could someone please give me any ideas how to fix this?

So whenever I run:
```
cd djinni_root_dir;
make example_android
```

or `make android`

I get this:

```
ANDROID_BUILD_TOP= deps/gyp/gyp --depth=. -f android -DOS=android -Icommon.gypi example/libtextsort.gyp --root-target=libtextsort_jni
Traceback (most recent call last):
  File "deps/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "deps/gyp/pylib/gyp/__init__.py", line 533, in script_main
    return main(sys.argv[1:])
  File "deps/gyp/pylib/gyp/__init__.py", line 526, in main
    return gyp_main(args)
  File "deps/gyp/pylib/gyp/__init__.py", line 511, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "deps/gyp/pylib/gyp/generator/android.py", line 970, in GenerateOutput
    assert android_top_dir, '$ANDROID_BUILD_TOP not set; you need to run lunch.'
AssertionError: $ANDROID_BUILD_TOP not set; you need to run lunch.
```

Search over error messages did not help. I know it comes somewhere from Android sources, still have no idea what to do. Should I set environment variable ANDROID_BUILD_TOP to some location?

**Comment by artwyman** [comment]
The Makefile is looking for ndk-build in your path in order to fill in ANDROID_BUILD_TOP, by calling `which ndk-build`.  You might need to add the appropriate directory to your PATH.

**Comment by RomanMinenok** [comment]
@artwyman Thank you very much for help and sorry for the stupid question, it was easy indeed, did not think about it. However now I get even stranger error when I am trying to build the project with `make example_android`: 
```
[armeabi-v7a] Compile++ thumb: textsort_jni <= NativeSortItems.cpp
In file included from ../../../example/generated-src/jni/NativeSortItems.hpp:6:0,
                 from ../../../example/generated-src/jni/NativeSortItems.cpp:4:
../../../support-lib/jni/djinni_support.hpp: In instantiation of 'const std::shared_ptr<_Tp1>& djinni::objectFromHandleAddress(jlong) [with T = textsort::SortItems; jlong = long long int]':
../../../example/generated-src/jni/NativeSortItems.cpp:29:93:   required from here
../../../support-lib/jni/djinni_support.hpp:352:81: internal compiler error: Segmentation fault: 11
     const auto & ret = reinterpret_cast<const CppProxyHandle<T> *>(handle)->get();
                                                                                 ^
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://source.android.com/source/report-bugs.html> for instructions.

:app:ndkBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:ndkBuild'.
> Process 'command '/Users/.../.../android-ndk-r10e/ndk-build'' finished with non-zero exit value 2
```
Could you give any hints on this as well?

**Comment by artwyman** [comment]
That's not something I've seen before, sorry.  Segfault in the compiler looks bad, but doesn't normally happen when building that example.

**Comment by fostah** [comment]
I can confirm that I'm seeing the same segmentation fault this morning while walking through this tutorial:

http://mobilecpptutorials.com/your-first-cross-platform-djinni-app-part-3-android/

**Comment by fostah** [comment]
So I rolled back to commit 2895f8f20f886a8bd4623a086ca72df5004643b0 from Sept 22 (README updates for CppCon 2015) and I was able to compile for Android. If I checkout the next commit, I start seeing compiler errors.

Hope this helps.

**Comment by j4cbo** [comment]
Exciting! :( I'll take a look tomorrow and see if I can get a repro.

**Comment by RomanMinenok** [comment]
Thanks guys, will try to build the example using the specified commit.

**Comment by j4cbo** [comment]
So the Android NDK includes builds of both gcc4.8 and gcc4.9. 4.8 is quite buggy, so we switched to 4.9 internally, but the example was still configured to build with 4.8. This particular issue seems to be a bug in gcc 4.8 that was fixed in 4.9, so the fix is just to use the newer compiler.

**Comment by RomanMinenok** [comment]
Thanks guys, will try to rebuild the example.

**Comment by ganeshskudva** [comment]
Hey guys, I am still seeing the same issue. 
I have **NDK_TOOLCHAIN_VERSION = 4.9** in my 

> example/android/app/jni/Application.mk

Any help?
